name: Build 1.21.1

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant permission to execute gradlew
        run: sudo chmod +x ./gradlew

      - name: Setup Files
        run: |
          ./gradlew fabric:setupFiles -Pminecraft_version="1.21.1" -Pminecraft_version_range="[1.21.1]" -Pparchment_minecraft_version="1.21.1" -Pparchment_mappings_version="2024.11.17" -Pneo_version="21.1.133" -Pneo_version_range="[21.1.133,)" -Pyarn_mappings="1.21.1+build.3" -Pfabric_version="0.115.1+1.21.1" -Pforge_version="52.1.0"
          ./gradlew forge:setupFiles -Pminecraft_version="1.21.1" -Pminecraft_version_range="[1.21.1]" -Pparchment_minecraft_version="1.21.1" -Pparchment_mappings_version="2024.11.17" -Pneo_version="21.1.133" -Pneo_version_range="[21.1.133,)" -Pyarn_mappings="1.21.1+build.3" -Pfabric_version="0.115.1+1.21.1" -Pforge_version="52.1.0"

      - name: Build with Gradle
        run: ./gradlew build -Pminecraft_version="1.21.1" -Pminecraft_version_range="[1.21.1]" -Pparchment_minecraft_version="1.21.1" -Pparchment_mappings_version="2024.11.17" -Pneo_version="21.1.133" -Pneo_version_range="[21.1.133,)" -Pyarn_mappings="1.21.1+build.3" -Pfabric_version="0.115.1+1.21.1" -Pforge_version="52.1.0"

      - name: Upload NeoForge artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./neoforge/build/libs/*
          name: The Pro's Game for NeoForge 1.21.1

      - name: Upload Fabric artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./fabric/build/libs/*
          name: The Pro's Game for Fabric 1.21.1

      - name: Upload Forge artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./forge/build/libs/*
          name: The Pro's Game for Forge 1.21.1