name: Build (All versions)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant permission to execute gradlew
        run: sudo chmod +x ./gradlew

      - name: Setup Files
        run: |
          ./gradlew fabric:setupFiles
          ./gradlew forge:setupFiles

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/forgix/*
          name: The Pro's Game