name: Upload to Archive.org
on: push

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install internetarchive

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Create bundle
        run: git bundle create pros_game-${{ github.sha }}.bundle --all

      - name: Upload file to archive.org
        run: |
          ia configure -u ${{ secrets.IA_USER }} -p ${{ secrets.IA_PWD }}
          ia upload pros_game-${{ github.sha }} pros_game-${{ github.sha }}.bundle --metadata="mediatype:software" --metadata="creator:Octagon Development" --metadata="title:pros_game-${{ github.sha }}" --metadata="scanner:The Pro's Game Auto-Archive" --metadata="collection:open_source_software" --metadata="subject:pro;Minecraft;mod;forge;fabric;architectuary;octagon development" --metadata="originalurl:https://github.com/Octagon-Modding/the-pros-game" --retries 20
